using System.Text.Json;
using Warden.Ml;

namespace Warden.Tests;

/// <summary>
/// Proves the C# byte-only EMBER feature groups (histogram, byte-entropy, strings = 616 dims) match the
/// Python reference (ml-training/ember_features.py) byte-for-byte, on deterministic buffers. Fixtures are
/// generated by ml-training/gen_byte_parity.py. This is the load-bearing parity guarantee for the parts of
/// the vector that do not depend on PE parsing.
/// </summary>
public sealed class EmberByteParityTests
{
    private sealed record Fixture(string Name, string Hex, double[] Histogram, double[] Byteentropy, double[] Strings);
    private sealed record FixtureFile(Fixture[] Fixtures);

    [Fact]
    public void Byte_groups_match_python_reference()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "parity", "byte_groups.json");
        Assert.True(File.Exists(path), $"parity fixtures missing at {path} (run ml-training/gen_byte_parity.py).");

        var file = JsonSerializer.Deserialize<FixtureFile>(
            File.ReadAllText(path), new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;
        Assert.NotEmpty(file.Fixtures);

        foreach (Fixture fx in file.Fixtures)
        {
            byte[] data = Convert.FromHexString(fx.Hex);
            AssertClose($"{fx.Name}.histogram", fx.Histogram, EmberFeatureExtractor.ByteHistogram(data));
            AssertClose($"{fx.Name}.byteentropy", fx.Byteentropy, EmberFeatureExtractor.ByteEntropyHistogram(data));
            AssertClose($"{fx.Name}.strings", fx.Strings, EmberFeatureExtractor.StringFeatures(data));
        }
    }

    private static void AssertClose(string label, double[] expected, double[] actual)
    {
        Assert.Equal(expected.Length, actual.Length);
        for (int i = 0; i < expected.Length; i++)
        {
            double diff = Math.Abs(expected[i] - actual[i]);
            double tol = 1e-5 + (1e-4 * Math.Abs(expected[i])); // float32 precision + cross-libm log2 ULP
            Assert.True(diff <= tol, $"{label}[{i}]: expected {expected[i]}, got {actual[i]} (diff {diff})");
        }
    }
}
