using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace Warden.Tests;

/// <summary>
/// Confirms the C# ONNX Runtime can load and score the onnxmltools-exported LightGBM model (the last
/// cross-language link). Runs against ml-training/artifacts/model.onnx when present (generated by
/// `python ml-training/train.py --smoke`); skips gracefully in CI where the artifact is absent.
/// </summary>
public sealed class OnnxScorerSmokeTests
{
    [Fact]
    public void Onnxmltools_export_loads_and_scores_in_csharp()
    {
        string? model = FindModel();
        if (model is null)
        {
            return; // artifact not generated in this environment; validated locally after train.py --smoke
        }

        using var session = new InferenceSession(model);
        string inputName = session.InputMetadata.Keys.First();
        var tensor = new DenseTensor<float>(new float[2381], new[] { 1, 2381 });
        using var results = session.Run(new[] { NamedOnnxValue.CreateFromTensor(inputName, tensor) });

        double score = 0d;
        foreach (var r in results)
        {
            if (r.Value is Tensor<float> t)
            {
                float[] arr = t.ToArray();
                score = arr.Length >= 2 ? arr[^1] : arr[0];
                break;
            }
        }

        Assert.InRange(score, 0.0, 1.0);
    }

    private static string? FindModel()
    {
        DirectoryInfo? dir = new(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Warden.sln")))
        {
            dir = dir.Parent;
        }
        if (dir is null)
        {
            return null;
        }
        string path = Path.Combine(dir.FullName, "ml-training", "artifacts", "model.onnx");
        return File.Exists(path) ? path : null;
    }
}
