<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Warden.Core\Warden.Core.csproj" />
    <ProjectReference Include="..\..\src\Warden.Storage\Warden.Storage.csproj" />
    <ProjectReference Include="..\..\src\Warden.Etw\Warden.Etw.csproj" />
    <ProjectReference Include="..\..\src\Warden.AttackChain\Warden.AttackChain.csproj" />
    <ProjectReference Include="..\..\src\Warden.Quarantine\Warden.Quarantine.csproj" />
    <ProjectReference Include="..\..\src\Warden.WebApps\Warden.WebApps.csproj" />
    <ProjectReference Include="..\..\src\Warden.AntiExploit\Warden.AntiExploit.csproj" />
    <ProjectReference Include="..\..\src\Warden.Firewall\Warden.Firewall.csproj" />
    <ProjectReference Include="..\..\src\Warden.Hardening\Warden.Hardening.csproj" />
  </ItemGroup>

</Project>
